### ISSUE TITLE
Update Content/Description on index.html

### ISSUE THREAD

**Issue by smartopian** [OpenConsent/ConsentReceipt#16]
1. Update the description. 
   - Developer resources to install, configure and deploy the Consent Receipt API and distributed web-based user-facing buttons. - 

To

"Developer resources to install, configure and deploy a demo of the CIS:MVCR 'Alpha' Consent Receipt specification,  and API demo. Including a distributed web-based user-facing button, to call the API."

**Comment by smartopian** [comment]
also needs a link of MVCR to Github Version of Specification at Kantara..   Can we convert MVCR Spec Word Doc into Github version and link it to Kantara Github Repo version of the specification?

**Comment by dazzaji** [comment]
Just link to the word doc till you figure out HTML or attract someone to the project who can do it. You may be unaware of the amount of time your changes to changes to changes are consuming for other people. So, no more changes.

**Comment by smartopian** [comment]
Dazza..  how are my changes making time for others please explain?  I need to make changes to the work you provided as it is not sufficent by itself. Word documents can auto generate HTML..  Not coding needed.

**Comment by dazzaji** [comment]
Evidently need to remind you of a few facts here:
1. regarding the characterization " the work you provided"
- Keep in mind that I have provided no work.  Work was provided by contractors.  What I provided to you was a guarantee that they would provide what you asked or if they did not, then I would do it and to them that you would pay them and if you did not then I would pay them.  
- I have also agreed to assist you with creating a footer reflecting the Kantara branding so that you can feel more comfortable forking the work to the Kantara site - that is something you should have specified in the requirements if you needed it but since you did not and you don't appear to be able to do it with ease on your own, I volunteer to do it for you and so I shall.  I have also volunteered to do much else, and have done so over a great many hours with you over the last couple of week free of charge, and have added much for you to the project as the commits to the repo reflect. 
- " ... the work... provided ...is not sufficent by itself."
- Keep in mind that you precisely noted 7 work items and had a careful mid-project walk through and an end-of-project walk through of the entire site before accepting the work as final from the contractors.  Any insufficiency is purely found in the project requirements - which are your responsibility.  

Make whatever changes you see fit, of course.  What I recommend is that you do not change the working repository by yourself any further due to the significant problems that many (most or nearly all) of your changes have caused thus far.  Instead, as suggested many times already, only make your changes to a cloned, forked or branched version and ensure everything looks and works the way it is supposed to before committing to the authoritative  version.  Better yet, involve people in the project who know what they are doing in GitHub to the extent you need to make changes to GitHub.  Better yet, accept the recommendation to only use the GitHub repo for the narrow purpose of being a working reference implementation of the API and client "button" with corresponding documentation and don't keep messing with that - and THEN use the Wordpress site at Kantara for all the other stuff you want to do related to the specification and community building.  That is nice and simple and it works.  You just point to the repo that is working - exactly as it was delivered to you or with only cosmetic changes - and fork that repo (for archive purposes) to the Kantara site.  Point to the working repo as a working reference implementation from the Kantara fork and the wordpress site and anywhere else you want people to see, test and fork a working project.
